--To create a table,modify and then describe it.
USE PRACTICE;
CREATE TABLE EMPLOYEE(EmpID int,Name VARCHAR(30),Salary FLOAT);
ALTER TABLE EMPLOYEE
ADD Department VARCHAR(25);
ALTER TABLE EMPLOYEE
MODIFY Salary FLOAT;
DESCRIBE EMPLOYEE;
ALTER TABLE EMPLOYEE
DROP COLUMN Department;
DESC EMPLOYEE;